export const products = [
  // {
  //     title: 'Hello Ram Kishore',
  //     subtitle: 'Welcome to Evaluate Health ',
  //     color1: '#E2DDD1',
  //     //color2: '#F3F1ED',
  //     color2: '#E2DDD1',
  //     // picture: require('../../../assets/icons/Digital1.png'),
  //     aspectRatio: 880 / 735,
  //     //navigateScreen: 'TrackerScreen',
  // },
  {
    title: 'Digitalize Health',
    subtitle: 'Let your trackers represent your Health ',
    color1: '#E2DDD1',
    //color2: '#F3F1ED',
    color2: '#E2DDD1',
    picture: require('../../../assets/icons/Digital1.png'),
    icon: require('../../../assets/Rectangle.png'),
    aspectRatio: 880 / 735,
    navigateScreen: 'TrackerScreen',
  },
  {
    title: 'Calendar for family',
    subtitle: 'Medical Schedulers as per your health condition',
    color1: '#b8bdd1',
    //color2: '#dcdde2',
    color2: '#b8bdd1',

    // picture: require('../../../assets/icons/calendar1.png'),
    picture: require('../../../assets/Rectangle1.png'),
    icon: require('../../../assets/Rectangle1.png'),
    aspectRatio: 880 / 735,
    navigateScreen: 'Calendar',
  },
  {
    title: 'Explore HealthTech',
    subtitle: 'One stop for all your healthcare needs',
    color1: '#c8d1db',
    //color2: '#e2e8ed',
    color2: '#c8d1db',
    picture: require('../../../assets/icons/Explore1.png'),
    icon: require('../../../assets/Rectangle.png'),

    aspectRatio: 880 / 735,
    navigateScreen: 'Database',
  },
  {
    icon: require('../../../assets/Rectangle1.png'),

    title: '360° Special Care',
    subtitle: 'Best care options for fast recovery',
    color1: '#e6d7d0',
    //color2: '#fff9f6',
    color2: '#e6d7d0',
    picture: require('../../../assets/icons/care.png'),
    aspectRatio: 880 / 735,
    navigateScreen: 'SpecialPackScreen',
  },
  {
    icon: require('../../../assets/Rectangle.png'),

    title: 'Personalize family ',
    subtitle: 'Works just like your trusted friend',
    // color1: '#a5d2bc',
    color1: '#badbca',
    color2: '#badbca',
    picture: require('../../../assets/icons/family.png'),
    aspectRatio: 880 / 735,
    navigateScreen: 'Profile',
  },
];
