{
  /*
   */
}
//   if stylesheet in same file >>>>>>>>>>>>>>
//import statements
// import {ThemeContext} from '../../../themes/components/ThemeContext';
// import {Colors} from '../../../themes';
// //state variables
// const {theme, toggleTheme} = React.useContext(ThemeContext);
// const Color = Colors(theme);
// const styles = getStyles(Color);

// // wrapping style

// const getStyles = Color => {
//   const style = StyleSheet.create({
//   });
//   return style;
// };

// //   if stylesheet in common file >>>>>>>>>>>>>>
// import getStyles from '../../utils/LoginStyles';
// import {ThemeContext} from '../../../../themes/components/ThemeContext';
// import {Colors} from '../../../../themes';
// //state
// const {theme, toggleTheme} = React.useContext(ThemeContext);
// const Color = Colors(theme);
// const styles = getStyles(Color);

// const styles = Color => {
//   const style = StyleSheet.create({});
//   return style;
// };

import {useContext} from 'react';
import {ThemeContext} from './components/ThemeContext';
import {file} from '@babel/types';
const updateTheme = theme => {
  //const {theme} = useContext(ThemeContext);
  let themes = theme;
  // let themes = 'dark';
  // let themes = 'light';
  //let themes = 'women';
  const COLOR =
    themes === 'dark'
      ? darkThemeColors
      : themes === 'women'
      ? womenThemeColors
      : lightThemeColors;
  const AllColors = {
    ...COLOR,
    ...commonColors,
  };
  return AllColors;
};

// Dark theme colors
export const darkThemeColors = {
  ...commonColors,

  //General >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //Global

  theme_textSubtitle: '#a1a2c3',
  arrowicon: '#86879E',
  theme_bgSecondary: '#363636',
  theme_card: '#202124',
  color1: '#7ce5e1', //OCR landing
  color2: '#2ecc7d',
  color3: '#8fb7f3',
  color4: '#AF8FE9',
  color5: '#e9e07a',
  theme_whiteLinear1: '#FFFFFF', //OCR>lock button
  theme_whiteLinear2: '#FFFFFF',
  theme_whiteLinear3: '#adadad',
  theme_whiteLinearIcon: '#86879E',
  //TextInputField Component
  textfieldContainer: '#363636',
  textfield_fontWrite: '#FFFFFF',
  textfield_fontInactive: '#f2f2f2',
  textfield_fontBaseColor: '#FFFFFF',
 
  //AppHeader Component
  headerTitle: '#86879E',
  headersubtitles: '#f2f2f2',
  badge_bg: '#86879E',
  badge: '#202124',
  buttonLinear1: '#FFFFFF', //home>bubble button
  buttonLinear2: '#FFFFFF',
  buttonLinear3: '#adadad',
  buttonlinearIcon: '#202124',
  header_iconInactive: '#86879E',
  header_iconActive: '#a1a2c3',

  //profileListSlider Component
  profileList_badge_bg: '#86879E',
  profileList_badge: '#202124',

  //Swiper
  swiper_bg: '#202124',
  swiper_activeColor: '#86879E',
  swiper_inactiveColor: '#656576',
  swiper_badgeColor: '#f5deb3',

  //ReadingContainer
  readingContainer_bg: '#202124',
  readingContainer_icon: '#86879E',
  readingContainer_title: '#c4c3c3',
  readingContainer_text: '#ffffff',
  readingContainer_badge: '#f5deb3',
  //Login & Welcome  >>>>>>>>>>>>>>>>>>>>>
  loader_bg: '#202124',
  linearFS1: '#202124',
  linearFS2: '#202124',
  linearFS3: '#202124',
  linearInactive: '#363636',
  li_bottomsheet_bg: '#363636',
  fontReadTheme: '#86879E',
  otpTimer: '#f5deb3',
  welcome_bg: '#202124',
  welcome_textfield_inactive: '#a3b3bf',
  welcome_icons: '#2899C6',
  welcome_textTitle: '#FFFFFF',
  welcome_textSubtitle: '#48d1cc',
  welcome_label: '#86879E',
  welcome_Submitbutton: '#FFFFFF',
  welcome_SubmitbuttonText: '#202124',
  //Home  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //bottomNav
  bottomNav_bg: '#202124',
  iconButtonActive: '#86879E',
  iconButtonInactive: '#585867',
  //HomeScreen
  linear1: '#202124',
  linear2: '#202124',
  linear3: '#202124',
  notification: '#f5deb3',
  notificationIcon: '#585867',
  themebackground: '#363636',

  feedBackground: '#202124',
  feedIconInactive: '#585867',
  feedIconActive: '#f5c8a2',
  feedIconlike: '#d52906',
  feedTextLike: '#FFFFFF',
  feedTextTitle: '#FFFFFF',
  feedTextSecondary: '#c4c3c3',
  feedHashtag: '#4af3f6',
  feedTextRead: '#FFFFFF',
  feedTextReadInactive: '#FFFFFF',
  feedComments: '#a3b3bf',
  feedTime: '#78858F',
  feedButton: '#86879E',
  feedButtonIcon: '#FFFFFF',
  feedButtonText: '#FFFFFF',
  feedBSheet_bg: '#363636',
  feedBSheet_bgHeader: '#676767',
  feedBSheet_bgHeaderdrgIcon: '#FFFFFF',
  feedBSheet_button: '#212124',
  feedBSheet_buttonText: '#FFFFFF',
  feedComment_commentText: '#dedede',
  feedComment_replylabel: '#999999',
  //TRACKER MODULE  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  track_bg: '#363636',
  track_card_bg: '#202124',
  track_button: '#86879E',
  track_buttonInactive: '#656576',
  track_titleText: '#FFFFFF',
  track_subtitle: '#c4c3c3',
  track_bottomsheet_dragIcon: '#86879E',
  track_buttoncancel: '#656576',
  track_buttonsave: '#86879E',
  track_buttonText: '#FFFFFF',
  track_hashtag: '#4af3f6',
  track_medicine: '#4af3f6',
  //OCR

  //TrackerLanding
  track_appHeader_iconInactive: '#86879E',
  track_overview_bg: '#363636',
  track_miniDash_linear1: '#656576',
  track_miniDash_linear2: '#86879E',
  track_miniDash_linear3: 'transparent',
  track_miniDash_focusText: '#f5c8a2',
  //TrackerDailyUpdate
  track_sidetitle: '#86879E',
  track_calendar: '#86879E',
  track_daily_chip: '#202124',
  track_daily_chipActive: '#86879E',
  track_daily_linear1: '#363636',
  track_daily_linear2: '#363636',
  track_daily_cardChip: '#86879E',
  track_daily_cardTitle: '#c4c3c3',
  track_daily_cardChipText: '#202124',
  track_daily_fontFocus: '#f5c8a2',
  //tracker_Details
  track_detail_linear1: '#202124',
  track_detail_linear2: '#202124',
  track_detail_linear3: '#202124',
  track_detail_header: '#f7f0f0',
  track_detail_subheader: '#86879E',
  track_detail_cardbg: '#202124',
  track_detail_cardBodybg: '#202124',
  track_detail_stackChartActive: '#86879E',
  track_detail_stackChartInActive: '#4a4a63',
  track_detail_stackChartLabel: '#c4c3c3',
  track_detail_frequencyActive: '#86879E',
  track_detail_frequencyInActive: '#363636', //dummy color
  track_detail_frequencyTextActive: '#202124',
  track_detail_frequencyTextInActive: '#f7f0f0', //dummy color
  track_detail_frequencyTime: '#f5c8a2',
  track_detail_frequencyTimeInactive: '#c4c3c3',
  track_detail_calendar_button: '#86879E',
  track_detail_calendar_buttonTextactive: '#f7f0f0',
  track_detail_calendar_buttonTextinactive: '#202124',
  track_linearSlider_bg: '#202124',
  track_linearSlider_line: '#4a4a63',
  track_linearSlider_thumb: '#4a4a63',
  track_linearSlider_thumbDetails: '#86879E',
  track_linearSlider_thumbDetailsTitle: '#202124',
  track_linearSlider_timeinSlider: '#202124',
  track_detail_calendar_bottomAdd: '#4a4a63',
  track_detail_calendar_bottomEdit: '#86879E',
  track_detail_separator: '#4a4a63',
  track_detail_footerbutton: '#5e5e7a',
  //Doctor Dashboard.
  track_linear1: '#c0bccb',
  track_linear2: '#b7b2c4',
  track_linear3: '#9892ab',
  track_linear4: '#8b84a0',
  track_linear5: '#7a7292',
  track_linear6: '#635c77',
  track_linear7: '#4c475c',
  track_linear8: '#353140',
  track_linear9: '#1e1c24',
  track_linear10: '#070709',
  track_linear_chipbg: '#e3e2e8',
  track_linear_chipText: '#202124',
  track_cardHighlight: '#86879E',
  track_cardHighlightText: '#202124',
  track_buttonFocus: '#f5c8a2',
  track_buttonTextInActive: '#202124',
  track_buttonTextFocus: '#202124',

  //CALENDAR  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  calen_bg: '#363636',
  calen_card_bg: '#202124',
  calen_card_title: '#FFFFFF',
  calen_card_subtitle: '#c4c3c3',
  calen_card_button: '#86879E',
  calen_card_buttonText: '#202124',
  calend_card_color1: '#86879E',
  calend_card_color2: '#F1C693',
  calend_card_textColor1: '#202124',
  calend_newtask_card_bgColor:'#BBBBBB',
  calend_newtask_endComponent_bgColor:'#171717',
  calend_icon_color1:"#BBBBBB",
  calend_txt_color1:"#FFFFFF",
  calend_txt_color2:'#FFFFFF',
  
  //EXPLORE  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  explore_appHeader_iconInactive: '#86879E',
  explore_bg: '#363636',
  explore_title: '#FFFFFF',
  explore_subtitle: '#13ada1',
  explore_medicineText: '#13ada1',
  explore_diseaseText: '#f5deb3',

  explore_card_bg: '#202124',
  explore_card_heading: '#13ada1',
  explore_card_title: '#FFFFFF',
  explore_card_subtitle: '#c4c3c3',
  explore_card_middletext: '#FFFFFF',
  explore_feedHashtag: '#4af3f6',
  explore_bigButton: '#13ada1',
  explore_bigButtonText: '#202124',
  explore_card_iconInactive: '#86879E',
  explore_card_iconActive: '#f5c8a2',
  explore_card_likeText: '#FFFFFF',

  //medicine
  explore_filterContainer: '#202124',
  explore_filterButton: '#86879E',
  explore_filterText: '#202124',
  //medicine details
  explore_highlightBackground: '#86879E',
  explore_chipbg: '#292929',
  explore_chiptext: '#FFFFFF',
  explore_userkeywordMatch: '#f5deb3',
  //MORE  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  more_bg: '#202124',
  more_card: '#363636',
  more_title: '#FFFFFF',
  more_subtitle: '#f5deb3',

  more_button: '#86879E',
  more_buttonActive: '#202124',
  more_cancel: '#a3b3bf',
  more_save: '#f5deb3',
  
  personal_profile:{
    icons:{
    activeColor:'#86879E',
    inactiveColor:'#ffffff',
    }
  },
  // Accounts Colors
  account_heading:'#FFFFFF',

  monochrome1: '#75cdf5',
  monochrome2: '#2899C6',
  monochrome3: '#7ce5e1',
  ////
  // settingsModalText: '#000000',
  // settingsModal: '#FFFFFF',
  WHITE: '#000000',
  white: '#f2f2f2',
  blue: '#00539b',
  lowBlue: '#4FA8D1',
  midBlue: '#2899C6',
  midHighBlue: '#1B88C3',
  highBlue: '#45a3e6',
  lightTurquoise: '#87dded',
  mediumturquoise: '#48d1cc',
  stdTurquoise: '#48CAE4',
  highTurquoise: '#189bb5',
  lightGray: '#a3b3bf',
  mildGray: '#78858F',
  mediumGray: '#536470',
  mildBlue: '#B6D9E7',
  aquaBlue: '#E5EDF7',
  mildAquaBlue: '#F4F9FF',
  highAquaBlue: '#c1d7f5',
  fullAqualBlue: '#8cb7f5',
  red: '#bf290b',
  darkgreen: '#47c047',
  paleOrange: '#ffe1c7',
  mildOrange: '#f5c8a2',
  mediumOrange: '#f0a86c',
  royalblue: '#4169e1',
};

// Light theme colors
export const lightThemeColors = {
  ...commonColors,

  //General >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //Global
  theme_textSubtitle: '#1B88C3', //personal profile slider text
  arrowicon: '#1B88C3', // arrow down up
  theme_bgSecondary: '#F4F9FF',
  theme_card: '#FFFFFF',
  color1: '#00539b', //OCR landing
  color2: '#32a7a3',
  color3: '#c08123',
  color4: '#636470',
  color5: '#9f31da',
  theme_whiteLinear1: '#FFFFFF', //OCR>lock button
  theme_whiteLinear2: '#FFFFFF',
  theme_whiteLinear3: '#c1bfbf',
  theme_whiteLinearIcon: '#157AC0',
  //TextInputField
  textfield_fontWrite: '#192030',
  textfield_fontInactive: '#157AC0',
  textfieldContainer: '#E5EDF7',
  textfield_fontBaseColor: '#014c8e',
  //AppHeader Component
  headerTitle: '#FFFFFF',
  headersubtitles: '#FFFFFF',
  badge_bg: '#FFFFFF',
  badge: '#157AC0',
  buttonLinear1: '#2899C6', //home>post icon
  buttonLinear2: '#1B88C3',
  buttonLinear3: '#157AC0',
  buttonlinearIcon: '#FFFFFF',
  header_iconInactive: '#B1D2F9',
  header_iconActive: '#FFFFFF',
  //profileListSlider Component
  profileList_badge_bg: '#1B88C3',
  profileList_badge: '#FFFFFF',
  //Swiper
  swiper_bg: '#157AC0',
  swiper_activeColor: '#FFFFFF',
  swiper_inactiveColor: '#adcbf4',
  swiper_badgeColor: '#f5deb3',
  //ReadingContainer
  readingContainer_bg: '#FFFFFF',
  readingContainer_icon: '#1B88C3',
  readingContainer_title: '#525252',
  readingContainer_text: '#000000',
  readingContainer_badge: '#f5deb3',
  //Login & Welcome  >>>>>>>>>>>>>>>>>>>>>>>>
  loader_bg: '#F4F9FF',
  linearFS1: '#2899C6',
  linearFS2: '#1B88C3',
  linearFS3: '#157AC0',
  linearInactive: '#4FA8D1',
  fontReadTheme: '#FFFFFF',
  li_bottomsheet_bg: '#2883c5',
  otpTimer: '#ffe1c7',
  welcome_bg: '#014c8e',
  welcome_icons: '#2899C6',
  welcome_textfield_inactive: '#a3b3bf',
  welcome_textTitle: '#FFFFFF',
  welcome_textSubtitle: '#48d1cc',
  welcome_label: '#157AC0',
  welcome_Submitbutton: '#FFFFFF',
  welcome_SubmitbuttonText: '#157AC0',
  //Home  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //BottomNav
  bottomNav_bg: '#FFFFFF',
  iconButtonActive: '#157AC0',
  iconButtonInactive: '#adcbf4',
  //home
  linear1: '#2899C6',
  linear2: '#1B88C3',
  linear3: '#157AC0',
  notification: '#585867',
  notificationIcon: '#c1d7f5',
  themebackground: '#E5EDF7',

  feedBackground: '#FFFFFF',
  feedIconInactive: '#adcbf4',
  feedIconActive: '#00539b',
  feedIconlike: '#7e1e0b',
  feedTextLike: '#000000',
  feedTextTitle: '#000000',
  feedTextSecondary: '#525252',
  feedHashtag: '#00539b',
  feedTextRead: '#78858F',
  feedTextReadInactive: '#536470',
  feedComments: '#78858F',
  feedTime: '#a3b3bf',
  feedButton: '#00539b',
  feedButtonIcon: '#FFFFFF',
  feedButtonText: '#FFFFFF',
  feedBSheet_bg: '#FFFFFF',
  feedBSheet_bgHeader: '#2899C6',
  feedBSheet_bgHeaderdrgIcon: '#FFFFFF',
  feedBSheet_button: '#2899C6',
  feedBSheet_buttonText: '#FFFFFF',
  feedComment_commentText: '#666666',
  feedComment_replylabel: '#999999',

  //TRACKER MODULE  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  track_bg: '#f2f2f2',
  track_card_bg: '#FFFFFF',
  track_button: '#f2f2f2',
  // track_buttonText: '#202124',
  track_titleText: '#202124',
  track_subtitle: '#525252',
  track_bottomsheet_dragIcon: '#00539b',
  track_buttoncancel: '#a3b3bf',
  track_buttonsave: '#00539b',
  track_buttonText: '#FFFFFF',
  track_hashtag: '#00539b',
  track_medicine: '#93f3f5',
  //OCR

  track_appHeader_iconInactive: '#FFFFFF',
  track_overview_bg: '#FFFFFF',
  track_miniDash_linear1: '#1B88C3',
  track_miniDash_linear2: '#2899C6',
  track_miniDash_linear3: 'transparent',
  track_miniDash_focusText: '#f5c8a2',
  //Tracker daily update
  track_sidetitle: '#202124',
  track_calendar: '#525252',
  track_daily_chip: '#F4F9FF',
  track_daily_chipActive: '#00539b',
  track_daily_linear1: '#6cc9d4',
  track_daily_linear2: '#50becc',
  track_daily_cardChip: '#a3dde4',
  track_daily_cardTitle: '#00539b',
  track_daily_cardChipText: '#00539b',
  //tracker_Details
  track_detail_linear1: '#157AC0',
  track_detail_linear2: '#157AC0',
  track_detail_linear3: '#157AC0',
  track_detail_header: '#FFFFFF',
  track_detail_subheader: '#E5EDF7',
  track_detail_cardbg: '#37b2c1',
  track_detail_cardBodybg: '#FFFFFF',
  track_detail_stackChartActive: '#48d1cc',
  track_detail_stackChartInActive: '#c4f5ea',
  track_detail_stackChartLabel: '#525252',
  track_detail_frequencyActive: '#48d1cc',
  track_detail_frequencyInActive: '#363636', //dummy color
  track_detail_frequencyTextActive: '#FFFFFF',
  track_detail_frequencyTextInActive: '#f7f0f0', //dummy color
  track_detail_frequencyTime: '#00539b',
  track_detail_frequencyTimeInactive: '#b5b3b3',
  track_detail_calendar_button: '#48d1cc',
  track_detail_calendar_buttonTextactive: '#00539b',
  track_detail_calendar_buttonTextinactive: '#FFFFFF',

  track_linearSlider_bg: '#E5EDF7',
  track_linearSlider_line: '#c4f5ea',
  track_linearSlider_thumb: '#37b2c1',
  track_linearSlider_thumbDetails: '#E5EDF7',
  track_linearSlider_thumbDetailsTitle: '#00539b',
  track_linearSlider_timeinSlider: '#686a71',
  track_detail_calendar_bottomAdd: '#37b2c1',
  track_detail_calendar_bottomEdit: '#74ceda',
  track_detail_separator: '#71e7e3',
  track_detail_footerbutton: '#2692a0',
  //Doctor Dashboard.
  track_linear1: '#a3dde4',
  track_linear2: '#88d3dc',
  track_linear3: '#6cc9d4',
  track_linear4: '#50becc',
  track_linear5: '#37b2c1',
  track_linear6: '#2f99a6',
  track_linear7: '#277f8a',
  track_linear8: '#1f656e',
  track_linear9: '#174c53',
  track_linear10: '#0f3237',
  track_linear_chipbg: '#baeef5',
  track_linear_chipText: '#034985',
  track_cardHighlight: '#50becc',
  track_cardHighlightText: '#ffffff',
  track_buttonFocus: '#f5c8a2',
  track_buttonInactive: '#50becc',
  track_buttonTextInActive: '#ffffff',
  track_buttonTextFocus: '#202124',
  //CALENDAR  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  calen_bg: '#f2f2f2',
  calen_card_bg: '#FFFFFF',
  calen_card_title: '#525252',
  calen_card_subtitle: '#78858F',
  calen_card_button: '#8cb7f5',
  calen_card_buttonText: '#00539b',
  calend_card_color1: '#00539b',
  calend_card_color2: '#78858F',
  calend_card_textColor1: '#FFFFFF',
  calend_newtask_card_bgColor:'#e2efff',
  calend_newtask_endComponent_bgColor:'#00539b',
  calend_icon_color1:"#00539b",
  calend_txt_color1:"#171717",
  calend_txt_color2:'#FFFFFF',
  //EXPLORE  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  explore_appHeader_iconInactive: '#FFFFFF',
  explore_bg: '#f2f2f2',
  explore_title: '#00539b',
  explore_subtitle: '#13ada1',
  explore_medicineText: '#13ada1',
  explore_diseaseText: '#e5b04c',

  explore_card_bg: '#FFFFFF',
  explore_card_heading: '#13ada1',
  explore_card_title: '#525252',
  explore_card_subtitle: '#78858F',
  explore_card_middletext: '#525252',
  explore_feedHashtag: '#00539b',
  explore_bigButton: '#13ada1',
  explore_bigButtonText: '#202124',

  explore_card_iconInactive: '#B1D2F9',
  explore_card_iconActive: '#f5c8a2',
  explore_card_likeText: '#00539b',

  //medicine
  explore_filterContainer: '#157AC0',
  explore_filterButton: '#B1D2F9',
  explore_filterText: '#00539b',
  //medicine details
  explore_highlightBackground: '#B1D2F9',
  explore_chipbg: '#F4F9FF',
  explore_chiptext: '#202124',
  explore_userkeywordMatch: '#f5deb3',
  //MORE  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  more_bg: '#e2efff',
  more_card: '#FFFFFF',
  more_title: '#FFFFFF',
  more_subtitle: '#f5deb3',

  more_button: '#286BBC',
  more_buttonActive: '#e2efff',
  more_cancel: '#90989f',
  more_save: '#00539b',
  
  //Personal Profile
  personal_profile:{
   icons:{
    activeColor:'#157AC0',
    inactiveColor:'#e2efff',
   }
  },
  // Accounts Colours
  account_heading:'#2899C6',
  

  monochrome1: '#2899C6',
  monochrome2: '#157AC0',
  monochrome3: '#00539b',
  //// Theme Hexcodes >>>>>>>>>>>>>>>>
  // settingsModalText: '#000000',
  // settingsModal: '#FFFFFF',
  WHITE: '#FFFFFF',
  white: '#f2f2f2',
  blue: '#00539b',
  lowBlue: '#4FA8D1',
  midBlue: '#2899C6',
  midHighBlue: '#1B88C3',
  highBlue: '#157AC0',
  lightTurquoise: '#87dded',
  mediumturquoise: '#48d1cc',
  stdTurquoise: '#48CAE4',
  highTurquoise: '#189bb5',
  lightGray: '#a3b3bf',
  mildGray: '#78858F',
  mediumGray: '#536470',
  mildBlue: '#B6D9E7',
  aquaBlue: '#E5EDF7',
  mildAquaBlue: '#F4F9FF',
  highAquaBlue: '#c1d7f5',
  fullAqualBlue: '#8cb7f5',
  red: '#bf290b',
  darkgreen: '#006400',
  paleOrange: '#ffe1c7',
  mildOrange: '#f5c8a2',
  mediumOrange: '#f0a86c',
  royalblue: '#4169e1',
};

//  women theme colors
export const womenThemeColors = {
  ...commonColors,
  //General >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //Global
  theme_textSubtitle: '#625b71',
  arrowicon: '#AF8FE9',
  theme_bgSecondary: '#f9f7ff',
  theme_card: '#FFFFFF',
  color1: '#00539b', //OCR landing
  color2: '#32a7a3',
  color3: '#c08123',
  color4: '#636470',
  color5: '#9f31da',
  theme_whiteLinear1: '#FFFFFF', //OCR>lock button
  theme_whiteLinear2: '#FFFFFF',
  theme_whiteLinear3: '#c1bfbf',
  theme_whiteLinearIcon: '#AF8FE9',
  //TextInputField Component
  textfield_fontWrite: '#192030',
  textfield_fontInactive: '#157AC0',
  textfieldContainer: '#E5EDF7',
  textfield_fontBaseColor: '#014c8e',
  //AppHeader Component
  headerTitle: '#FFFFFF',
  headersubtitles: '#FFFFFF',
  badge_bg: '#FFFFFF',
  badge: '#AF8FE9',

  buttonLinear1: '#DCCFFE', //home>post icon
  buttonLinear2: '#AF8FE9',
  buttonLinear3: '#AF8FE9',
  buttonlinearIcon: '#f2f2f2',
  // buttonlinearIconActive: '#4926a3',
  header_iconInactive: '#DCCFFE',
  header_iconActive: '#FFFFFF',

  //profileListSlider Component
  profileList_badge_bg: '#AF8FE9',
  profileList_badge: '#FFFFFF',

  //Swiper
  swiper_bg: '#AF8FE9',
  swiper_activeColor: '#FFFFFF',
  swiper_inactiveColor: '#DCCFFE',
  swiper_badgeColor: '#585867',

  //ReadingContainer
  readingContainer_bg: '#FFFFFF',
  readingContainer_icon: '#AF8FE9',
  readingContainer_title: '#525252',
  readingContainer_text: '#000000',
  readingContainer_badge: '#f5deb3',
  //Login & Welcome  >>>>>>>>>>>>>>>>>>>>>>>>>>
  loader_bg: '#f9f7ff',
  linearFS1: '#c3b1f1',
  linearFS2: '#AF8FE9',
  linearFS3: '#AF8FE9',
  linearInactive: '#936aca',
  li_bottomsheet_bg: '#a27fe3',
  fontReadTheme: '#FFFFFF',
  otpTimer: '#585867',
  welcome_bg: '#AF8FE9',
  welcome_icons: '#2899C6',
  welcome_textfield_inactive: '#e3daf9',
  welcome_textTitle: '#FFFFFF',
  welcome_textSubtitle: '#192030',
  welcome_label: '#DCCFFE',
  welcome_Submitbutton: '#FFFFFF',
  welcome_SubmitbuttonText: '#AF8FE9',
  //Home  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //bottomNav
  bottomNav_bg: '#FFFFFF',
  iconButtonActive: '#AF8FE9',
  iconButtonInactive: '#DCCFFE',

  linear1: '#AF8FE9',
  linear2: '#AF8FE9',
  linear3: '#AF8FE9',
  notification: '#585867',
  notificationIcon: '#FCDCDB',
  themebackground: '#f5f2fc',

  //feed
  feedBackground: '#FFFFFF',
  feedIconInactive: '#DCCFFE',
  feedIconActive: '#AF8FE9',
  feedIconlike: '#7e1e0b',
  feedTextLike: '#000000',
  feedTextTitle: '#192030',
  feedTextSecondary: '#585867',
  feedHashtag: '#00539b',
  feedTextRead: '#585867',
  feedTextReadInactive: '#585867',
  feedComments: '#78858F',
  feedTime: '#a3b3bf',
  feedButton: '#AF8FE9',
  feedButtonIcon: '#FFFFFF',
  feedButtonText: '#FFFFFF',
  feedBSheet_bg: '#FFFFFF',
  feedBSheet_bgHeader: '#AF8FE9',
  feedBSheet_bgHeaderdrgIcon: '#FFFFFF',
  feedBSheet_button: '#AF8FE9',
  feedBSheet_buttonText: '#FFFFFF',
  feedComment_commentText: '#666666',
  feedComment_replylabel: '#999999',
  // fontLinearPrimary: '#FCDCDB',
  // BACKGROUND: '#E9AB8C',
  // background: '#F5D4C1',
  // themeBACKGROUND: '#E9A4C2',

  //Tracker  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  track_bg: '#f2f2f2',
  track_card_bg: '#FFFFFF',
  track_button: '#f2f2f2',
  //track_buttonText: '#202124',
  track_titleText: '#202124',
  track_subtitle: '#525252',
  track_bottomsheet_dragIcon: '#AF8FE9',
  track_buttoncancel: '#E9AB8C',
  track_buttonsave: '#AF8FE9',
  track_buttonText: '#FFFFFF',
  track_hashtag: '#00539b',
  track_medicine: '#4af3f6',
  //OCR
  track_appHeader_iconInactive: '#FFFFFF',
  track_overview_bg: '#FFFFFF',
  track_miniDash_linear1: '#554C74',
  track_miniDash_linear2: '#796DA8',
  track_miniDash_linear3: 'transparent',
  // track_miniDash_linear1: '#AF8FE9',
  // track_miniDash_linear2: '#c3a7f7',
  // track_miniDash_linear3: 'transparent',
  track_miniDash_focusText: '#f9d9bf',

  //TrackerDailyUpdate
  track_sidetitle: '#86879E',
  track_calendar: '#86879E',
  track_daily_chip: '#f9f7ff',
  track_daily_chipActive: '#554C74',
  track_daily_linear1: '#6cc9d4',
  track_daily_linear2: '#50becc',
  track_daily_cardChip: '#a3dde4',
  track_daily_cardTitle: '#554C74',
  track_daily_cardChipText: '#554C74',
  //tracker_Details
  track_detail_linear1: '#AF8FE9',
  track_detail_linear2: '#AF8FE9',
  track_detail_linear3: '#AF8FE9',
  track_detail_header: '#ffffff',
  track_detail_subheader: '#E5EDF7',
  track_detail_cardbg: '#554C74',
  track_detail_cardBodybg: '#FFFFFF',
  track_detail_stackChartActive: '#4a4a63',
  track_detail_stackChartInActive: '#86879E',
  track_detail_stackChartLabel: '#525252',
  track_detail_frequencyActive: '#AF8FE9',
  track_detail_frequencyInActive: '#363636', //dummy color
  track_detail_frequencyTextActive: '#FFFFFF',
  track_detail_frequencyTextInActive: '#f7f0f0', //dummy color
  track_detail_frequencyTime: '#4a4a63',
  track_detail_frequencyTimeInactive: '#b5b3b3',
  track_detail_calendar_button: '#AF8FE9',
  track_detail_calendar_buttonTextactive: '#4a4a63',
  track_detail_calendar_buttonTextinactive: '#FFFFFF',

  track_linearSlider_bg: '#E5EDF7',
  track_linearSlider_line: '#b9b1d7',
  track_linearSlider_thumb: '#AF8FE9',
  track_linearSlider_thumbDetails: '#E5EDF7',
  track_linearSlider_thumbDetailsTitle: '#00539b',
  track_linearSlider_timeinSlider: '#686a71',
  track_detail_calendar_bottomAdd: '#AF8FE9',
  track_detail_calendar_bottomEdit: '#8f81bf',
  track_detail_separator: '#b9b1d7',
  track_detail_footerbutton: '#3a305e',

  //Doctor Dashboard.
  track_linear1: '#b9b1d7',
  track_linear2: '#a499cb',
  track_linear3: '#8f81bf',
  track_linear4: '#7a6ab3',
  track_linear5: '#6654a5',
  track_linear6: '#57488e',
  track_linear7: '#483c76',
  track_linear8: '#3a305e',
  track_linear9: '#2b2447',
  track_linear10: '#1d182f',
  track_linear_chipbg: '#dad4f2',
  track_linear_chipText: '#202124',
  track_buttonTextInActive: '#ffffff',
  track_buttonTextFocus: '#202124',
  track_cardHighlight: '#8f81bf',
  track_cardHighlightText: '#ffffff',
  track_buttonFocus: '#f5c8a2',
  track_buttonInactive: '#8f81bf',
  //CALENDAR  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  calen_bg: '#f5f2fc',
  calen_card_bg: '#FFFFFF',
  calen_card_title: '#525252',
  calen_card_subtitle: '#78858F',
  calen_card_button: '#DCCFFE',
  calen_card_buttonText: '#9368e4',
  calend_card_color1: '#AF8FE9',
  calend_card_color2: '#3AC4A4',
  calend_card_textColor1: '#FFFFFF',
  calend_newtask_card_bgColor:'#DCCFFE',
  calend_newtask_endComponent_bgColor:'#9368e4',
  calend_icon_color1:"#AF8FE9",
  calend_txt_color1:"#171717",
  calend_txt_color2:'#FFFFFF',
  //EXPLORE  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  explore_appHeader_iconInactive: '#FFFFFF',
  explore_bg: '#f5f2fc',
  explore_title: '#00539b',
  explore_subtitle: '#13ada1',
  explore_medicineText: '#13ada1',
  explore_diseaseText: '#e5b04c',
  explore_card_bg: '#FFFFFF',
  explore_card_heading: '#13ada1',
  explore_card_title: '#525252',
  explore_card_subtitle: '#78858F',
  explore_card_middletext: '#525252',
  explore_feedHashtag: '#00539b',
  explore_bigButton: '#13ada1',
  explore_bigButtonText: '#202124',

  explore_card_iconInactive: '#f2f2f2',
  explore_card_iconActive: '#f5c8a2',
  explore_card_likeText: '#00539b',

  //medicine
  explore_filterContainer: '#AF8FE9',
  explore_filterButton: '#DCCFFE',
  explore_filterText: '#8352df',
  //medicine details
  explore_highlightBackground: '#DCCFFE',
  explore_chipbg: '#f5f2fc',
  explore_chiptext: '#202124',
  explore_userkeywordMatch: '#f5deb3',
  //MORE  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  more_bg: '#efe9ff',
  more_card: '#FFFFFF',
  more_title: '#FFFFFF',
  more_subtitle: '#C3E6E0',
  more_button: '#E98F9C',
  more_buttonActive: '#eff6f9',
  more_cancel: '#90989f',
  more_save: '#9368e4',

   //Personal Profile

   personal_profile:{
    icons:{
     activeColor:'#E98F9C',
     inactiveColor:'#FFFFFF',
    }
  },
  // Accounts Colors

  account_heading:'#E98F9C',

  monochrome1: '#2899C6',
  monochrome2: '#157AC0',
  monochrome3: '#00539b',
  ///////
  // settingsModalText: '#000000',
  // settingsModal: '#FFFFFF',
  WHITE: '#FFFFFF',
  white: '#f2f2f2',
  blue: '#00539b',
  lowBlue: '#4FA8D1',
  midBlue: '#2899C6',
  midHighBlue: '#1B88C3',
  highBlue: '#157AC0',
  lightTurquoise: '#87dded',
  mediumturquoise: '#48d1cc',
  stdTurquoise: '#48CAE4',
  highTurquoise: '#189bb5',
  lightGray: '#a3b3bf',
  mildGray: '#78858F',
  mediumGray: '#536470',
  mildBlue: '#B6D9E7',
  aquaBlue: '#E5EDF7',
  mildAquaBlue: '#F4F9FF',
  highAquaBlue: '#c1d7f5',
  fullAqualBlue: '#8cb7f5',
  red: '#bf290b',
  darkgreen: '#006400',
  paleOrange: '#ffe1c7',
  mildOrange: '#f5c8a2',
  mediumOrange: '#f0a86c',
  royalblue: '#4169e1',
};

// Pregnant women/child theme colors
export const pregnantwomenThemeColors = {
  ...commonColors,
  //General >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //TextInputField Component
  fontWrite: '#192030',
  fontInactive: '#FFFFFF',
  //AppHeader Component
  headerTitle: '#FFFFFF',
  headersubtitles: '#FFFFFF',
  badge_bg: '#FFFFFF',
  badge: '#f38a85',

  buttonLinear1: '#f4c3c1', //home>post icon
  buttonLinear2: '#F9A7A2',
  buttonLinear3: '#F9A7A2',
  buttonlinearIcon: '#f2f2f2',
  //Login & Welcome  >>>>>>>>>>>>>>>>>>>>>>>>>>
  linearFS1: '#f4c3c1',
  linearFS2: '#F9A7A2',
  linearFS3: '#F9A7A2',
  linearInactive: '#f38a85',
  li_bottomsheet_bg: '#f38a85',
  fontReadTheme: '#FFFFFF',
  otpTimer: '#585867',
  welcome_bg: '#f4c3c1',
  welcome_icons: '#2899C6',
  welcome_textTitle: '#FFFFFF',
  welcome_textSubtitle: '#192030',
  welcome_label: '#86879E',

  //Home  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //bottomNav
  bottomNav_bg: '#FFFFFF',
  iconButtonActive: '#ee7f7a',
  iconButtonInactive: '#fbc6c4',

  linear1: '#F9A7A2',
  linear2: '#F9A7A2',
  linear3: '#F9A7A2',
  notification: '#585867',
  notificationIcon: '#FCDCDB',
  themebackground: '#faeded',

  //feed
  feedBackground: '#FFFFFF',
  feedIconInactive: '#fbc6c4',
  feedIconActive: '#ee7f7a',
  feedIconlike: '#7e1e0b',
  feedTextTitle: '#192030',
  feedTextSecondary: '#585867',
  feedHashtag: '#00539b',
  feedTextRead: '#585867',
  feedTextReadInactive: '#585867',
  feedComments: '#78858F',
  feedTime: '#a3b3bf',

  // fontLinearPrimary: '#FCDCDB',
  // BACKGROUND: '#E9AB8C',
  // background: '#F5D4C1',
  // themeBACKGROUND: '#E9A4C2',

  ///////

  WHITE: '#FFFFFF',
  white: '#f2f2f2',
  blue: '#00539b',
  lowBlue: '#4FA8D1',
  midBlue: '#2899C6',
  midHighBlue: '#1B88C3',
  highBlue: '#157AC0',
  lightTurquoise: '#87dded',
  mediumturquoise: '#48d1cc',
  stdTurquoise: '#48CAE4',
  highTurquoise: '#189bb5',
  lightGray: '#a3b3bf',
  mildGray: '#78858F',
  mediumGray: '#536470',
  mildBlue: '#B6D9E7',
  aquaBlue: '#E5EDF7',
  mildAquaBlue: '#F4F9FF',
  highAquaBlue: '#c1d7f5',
  fullAqualBlue: '#8cb7f5',
  red: '#bf290b',
  paleOrange: '#ffe1c7',
  mildOrange: '#f5c8a2',
  mediumOrange: '#f0a86c',
};
//// *********************** Others *************************
const commonColors = {
  common_WHITE: '#FFFFFF',
  common_white: '#f2f2f2',
  common_blue: '#00539b',
  common_lowBlue: '#4FA8D1',
  common_midBlue: '#2899C6',
  common_midHighBlue: '#1B88C3',
  common_highBlue: '#157AC0',
  common_lightTurquoise: '#87dded',
  common_mediumturquoise: '#48d1cc',
  common_stdTurquoise: '#48CAE4',
  common_highTurquoise: '#189bb5',
  common_lightGray: '#a3b3bf',
  common_mildGray: '#78858F',
  common_mediumGray: '#536470',
  common_mildBlue: '#B6D9E7',
  common_aquaBlue: '#E5EDF7',
  common_mildAquaBlue: '#F4F9FF',
  common_highAquaBlue: '#c1d7f5',
  common_fullAqualBlue: '#8cb7f5',
  common_red: '#bf290b',
  common_paleOrange: '#ffe1c7',
  common_mildOrange: '#f5c8a2',
  common_mediumOrange: '#f0a86c',
  aliceblue: '#f0f8ff',
  antiquewhite: '#faebd7',
  aqua: '#00ffff',
  aquamarine: '#7fffd4',
  azure: '#f0ffff',
  beige: '#f5f5dc',
  bisque: '#ffe4c4',
  common_BLACK: '#000000',
  midblack: 'rgba(0,0,0,0.8)',
  blanchedalmond: '#ffebcd',
  blueviolet: '#8a2be2',
  brightred: '#ff0000',
  brown: '#a52a2a',
  burlywood: '#deb887',
  cadetblue: '#5f9ea0',
  chartreuse: '#7fff00',
  chocolate: '#d2691e',
  coral: '#ff7f50',
  cornflowerblue: '#6495ed',
  cornsilk: '#fff8dc',
  crimson: '#dc143c',
  cyan: '#00ffff',
  darkblue: '#00008b',
  darkcyan: '#008b8b',
  darkgoldenrod: '#b8860b',
  darkgray: '#a9a9a9',
  darkgreen: '#006400',
  darkkhaki: '#bdb76b',
  darkmagenta: '#8b008b',
  darkolivegreen: '#556b2f',
  darkorange: '#ff8c00',
  darkorchid: '#9932cc',
  darkred: '#8b0000',
  darksalmon: '#e9967a',
  darkseagreen: '#8fbc8f',
  darkslateblue: '#483d8b',
  darkslategray: '#2f4f4f',
  darkturquoise: '#00ced1',
  darkviolet: '#9400d3',
  deeppink: '#ff1493',
  deepskyblue: '#00bfff',
  dimgray: '#696969',
  dodgerblue: '#1e90ff',
  firebrick: '#b22222',
  floralwhite: '#fffaf0',
  forestgreen: '#228b22',
  fuchsia: '#ff00ff',
  gainsboro: '#dcdcdc',
  ghostwhite: '#f8f8ff',
  gold: '#ffd700',
  goldenrod: '#daa520',
  greenyellow: '#adff2f',
  gray: '#808080',
  honeydew: '#f0fff0',
  hotpink: '#ff69b4',
  indianred: '#cd5c5c',
  indigo: '#4b0082',
  ivory: '#fffff0',
  khaki: '#f0e68c',
  lavender: '#e6e6fa',
  lavenderblush: '#fff0f5',
  lawngreen: '#7cfc00',
  lemonchiffon: '#fffacd',
  lightblue: '#add8e6',
  lightcoral: '#f08080',
  lightcyan: '#e0ffff',
  lightgoldenrodyellow: '#fafad2',
  lightgreen: '#90ee90',
  lightpink: '#ffb6c1',
  lightsalmon: '#ffa07a',
  lightseagreen: '#20b2aa',
  lightskyblue: '#87cefa',
  lightslategray: '#778899',
  lightsteelblue: '#b0c4de',
  lightyellow: '#ffffe0',
  lime: '#00ff00',
  limegreen: '#32cd32',
  linen: '#faf0e6',
  magenta: '#ff00ff',
  maroon: '#800000',
  mediumaquamarine: '#66cdaa',
  midnightblue: '#191970',
  mintcream: '#f5fffa',
  mistyrose: '#ffe4e1',
  moccasin: '#ffe4b5',
  navajowhite: '#ffdead',
  navy: '#000080',
  oldlace: '#fdf5e6',
  olive: '#808000',
  olivedrab: '#6b8e23',
  orange: '#ffa500',
  orangered: '#ff4500',
  orchid: '#da70d6',
  palegoldenrod: '#eee8aa',
  palegray: '#d3d3d3',
  palegreen: '#98fb98',
  paleturquoise: '#afeeee',
  palevioletred: '#db7093',
  papayawhip: '#ffefd5',
  peachpuff: '#ffdab9',
  peru: '#cd853f',
  pink: '#ffc0cb',
  plum: '#dda0dd',
  powderblue: '#b0e0e6',
  purple: '#800080',
  rebeccapurple: '#663399',
  rosybrown: '#bc8f8f',
  royalblue: '#4169e1',
  royalblueDark: '#0457fd',
  saddlebrown: '#8b4513',
  salmon: '#fa8072',
  sandybrown: '#f4a460',
  seagreen: '#2e8b57',
  seashell: '#fff5ee',
  sienna: '#a0522d',
  silver: '#c0c0c0',
  skyblue: '#87ceeb',
  slateblue: '#6a5acd',
  slategray: '#708090',
  snow: '#fffafa',
  springgreen: '#00ff7f',
  steelblue: '#4682b4',
  tan: '#d2b48c',
  teal: '#008080',
  thistle: '#d8bfd8',
  tomato: '#ff6347',
  turquoise: '#40e0d0',
  violet: '#ee82ee',
  wheat: '#f5deb3',
  whitesmoke: '#f5f5f5',
  yellow: '#ffd200',
};

export const Color = lightThemeColors;
// Call the updateTheme() function to initialize the UI with the default theme
export default updateTheme;

/////////// Old Light mode..................
// export default {
//   WHITE: '#FFFFFF',
//   white: '#f2f2f2',
//   blue: '#00539b',

//   //// *********************** IN Use for Evaluate Health *************************

//   lowBlue: '#4FA8D1', /// lineargradient opacity feel
//   midBlue: '#2899C6', /// lineargradient lowest color
//   midHighBlue: '#1B88C3', /// lineargradient middle color
//   highBlue: '#157AC0', /// lineargradient high color

//   lightTurquoise: '#87dded',
//   mediumturquoise: '#48d1cc',
//   stdTurquoise: '#48CAE4',
//   highTurquoise: '#189bb5',
//   lightGray: '#a3b3bf',
//   mildGray: '#78858F', //Readable text content
//   mediumGray: '#536470',

//   mildBlue: '#B6D9E7', //blue lineargradient inactive color
//   aquaBlue: '#E5EDF7', // textfields,
//   mildAquaBlue: '#F4F9FF', //chipbackground
//   highAquaBlue: '#c1d7f5',
//   fullAqualBlue: '#8cb7f5',
//   red: '#bf290b', // error messages,
//   paleOrange: '#ffe1c7', // backgrounds
//   mildOrange: '#f5c8a2', // textfields,
//   mediumOrange: '#f0a86c',

//   //// *********************** Others *************************
//   aliceblue: '#f0f8ff',
//   antiquewhite: '#faebd7',
//   aqua: '#00ffff',
//   aquamarine: '#7fffd4',
//   azure: '#f0ffff',
//   beige: '#f5f5dc',
//   bisque: '#ffe4c4',
//   BLACK: '#000000',
//   midblack: 'rgba(0,0,0,0.8)',
//   blanchedalmond: '#ffebcd',
//   blueviolet: '#8a2be2',
//   brightred: '#ff0000',
//   brown: '#a52a2a',
//   burlywood: '#deb887',
//   cadetblue: '#5f9ea0',
//   chartreuse: '#7fff00',
//   chocolate: '#d2691e',
//   coral: '#ff7f50',
//   cornflowerblue: '#6495ed',
//   cornsilk: '#fff8dc',
//   crimson: '#dc143c',
//   cyan: '#00ffff',
//   darkblue: '#00008b',
//   darkcyan: '#008b8b',
//   darkgoldenrod: '#b8860b',
//   darkgray: '#a9a9a9',
//   darkgreen: '#006400',
//   darkkhaki: '#bdb76b',
//   darkmagenta: '#8b008b',
//   darkolivegreen: '#556b2f',
//   darkorange: '#ff8c00',
//   darkorchid: '#9932cc',
//   darkred: '#8b0000',
//   darksalmon: '#e9967a',
//   darkseagreen: '#8fbc8f',
//   darkslateblue: '#483d8b',
//   darkslategray: '#2f4f4f',
//   darkturquoise: '#00ced1',
//   darkviolet: '#9400d3',
//   deeppink: '#ff1493',
//   deepskyblue: '#00bfff',
//   dimgray: '#696969',
//   dodgerblue: '#1e90ff',
//   firebrick: '#b22222',
//   floralwhite: '#fffaf0',
//   forestgreen: '#228b22',
//   fuchsia: '#ff00ff',
//   gainsboro: '#dcdcdc',
//   ghostwhite: '#f8f8ff',
//   gold: '#ffd700',
//   goldenrod: '#daa520',
//   greenyellow: '#adff2f',
//   gray: '#808080',
//   honeydew: '#f0fff0',
//   hotpink: '#ff69b4',
//   indianred: '#cd5c5c',
//   indigo: '#4b0082',
//   ivory: '#fffff0',
//   khaki: '#f0e68c',
//   lavender: '#e6e6fa',
//   lavenderblush: '#fff0f5',
//   lawngreen: '#7cfc00',
//   lemonchiffon: '#fffacd',
//   lightblue: '#add8e6',
//   lightcoral: '#f08080',
//   lightcyan: '#e0ffff',
//   lightgoldenrodyellow: '#fafad2',
//   lightgreen: '#90ee90',
//   lightpink: '#ffb6c1',
//   lightsalmon: '#ffa07a',
//   lightseagreen: '#20b2aa',
//   lightskyblue: '#87cefa',
//   lightslategray: '#778899',
//   lightsteelblue: '#b0c4de',
//   lightyellow: '#ffffe0',
//   lime: '#00ff00',
//   limegreen: '#32cd32',
//   linen: '#faf0e6',
//   magenta: '#ff00ff',
//   maroon: '#800000',
//   mediumaquamarine: '#66cdaa',
//   midnightblue: '#191970',
//   mintcream: '#f5fffa',
//   mistyrose: '#ffe4e1',
//   moccasin: '#ffe4b5',
//   navajowhite: '#ffdead',
//   navy: '#000080',
//   oldlace: '#fdf5e6',
//   olive: '#808000',
//   olivedrab: '#6b8e23',
//   orange: '#ffa500',
//   orangered: '#ff4500',
//   orchid: '#da70d6',
//   palegoldenrod: '#eee8aa',
//   palegray: '#d3d3d3',
//   palegreen: '#98fb98',
//   paleturquoise: '#afeeee',
//   palevioletred: '#db7093',
//   papayawhip: '#ffefd5',
//   peachpuff: '#ffdab9',
//   peru: '#cd853f',
//   pink: '#ffc0cb',
//   plum: '#dda0dd',
//   powderblue: '#b0e0e6',
//   purple: '#800080',
//   rebeccapurple: '#663399',
//   rosybrown: '#bc8f8f',
//   royalblue: '#4169e1',
//   royalblueDark: '#0457fd',
//   saddlebrown: '#8b4513',
//   salmon: '#fa8072',
//   sandybrown: '#f4a460',
//   seagreen: '#2e8b57',
//   seashell: '#fff5ee',
//   sienna: '#a0522d',
//   silver: '#c0c0c0',
//   skyblue: '#87ceeb',
//   slateblue: '#6a5acd',
//   slategray: '#708090',
//   snow: '#fffafa',
//   springgreen: '#00ff7f',
//   steelblue: '#4682b4',
//   tan: '#d2b48c',
//   teal: '#008080',
//   thistle: '#d8bfd8',
//   tomato: '#ff6347',
//   turquoise: '#40e0d0',
//   violet: '#ee82ee',
//   wheat: '#f5deb3',
//   whitesmoke: '#f5f5f5',
//   yellow: '#ffd200',
// };

/// attempt for Dark theme
// export default {
//   background: '#282828',
//   BACKGROUND: '#1A1A1A',

//   fontlight: '#a2a3a3',
//   font: '#E9E9E9',
//   FONT: '#827F86',
//   fontContrast: '#c7f9f8',

//   iconContrastP: '#E7A56E',
//   iconlight: '#6b696e',
//   iconActive: '#a2ccf1',
//   /// before themes.............................
//   WHITE: '#3f3d3d',
//   white: '#3F4346',
//   blue: '#a2ccf1',

//   //// *********************** IN Use for Evaluate Health *************************

//   lowBlue: '#4FA8D1', /// lineargradient opacity feel
//   midBlue: '#2899C6', /// lineargradient lowest color
//   midHighBlue: '#1B88C3', /// lineargradient middle color
//   highBlue: '#157AC0', /// lineargradient high color

//   lightTurquoise: '#87dded',
//   mediumturquoise: '#48d1cc',
//   stdTurquoise: '#48CAE4',
//   highTurquoise: '#189bb5',
//   lightGray: '#a2a3a3',
//   mildGray: '#aaafb4', //Readable text content
//   mediumGray: '#979b9e',

//   mildBlue: '#B6D9E7', //blue lineargradient inactive color
//   aquaBlue: '#1f1c1c', // textfields,
//   mildAquaBlue: '#F4F9FF', //chipbackground
//   highAquaBlue: '#c1d7f5',
//   fullAqualBlue: '#8cb7f5',
//   red: '#bf290b', // error messages,
//   paleOrange: '#ffe1c7', // backgrounds
//   mildOrange: '#f5c8a2', // textfields,
//   mediumOrange: '#f0a86c',

//   //// *********************** Others *************************
//   aliceblue: '#f0f8ff',
//   antiquewhite: '#faebd7',
//   aqua: '#00ffff',
//   aquamarine: '#7fffd4',
//   azure: '#f0ffff',
//   beige: '#f5f5dc',
//   bisque: '#ffe4c4',
//   BLACK: '#fffefe',
//   midblack: 'rgba(104, 104, 104, 0.8)',
//   blanchedalmond: '#ffebcd',
//   blueviolet: '#8a2be2',
//   brightred: '#ff0000',
//   brown: '#a52a2a',
//   burlywood: '#deb887',
//   cadetblue: '#5f9ea0',
//   chartreuse: '#7fff00',
//   chocolate: '#d2691e',
//   coral: '#ff7f50',
//   cornflowerblue: '#6495ed',
//   cornsilk: '#fff8dc',
//   crimson: '#dc143c',
//   cyan: '#00ffff',
//   darkblue: '#00008b',
//   darkcyan: '#008b8b',
//   darkgoldenrod: '#b8860b',
//   darkgray: '#a9a9a9',
//   darkgreen: '#006400',
//   darkkhaki: '#bdb76b',
//   darkmagenta: '#8b008b',
//   darkolivegreen: '#556b2f',
//   darkorange: '#ff8c00',
//   darkorchid: '#9932cc',
//   darkred: '#8b0000',
//   darksalmon: '#e9967a',
//   darkseagreen: '#8fbc8f',
//   darkslateblue: '#483d8b',
//   darkslategray: '#2f4f4f',
//   darkturquoise: '#00ced1',
//   darkviolet: '#9400d3',
//   deeppink: '#ff1493',
//   deepskyblue: '#00bfff',
//   dimgray: '#696969',
//   dodgerblue: '#1e90ff',
//   firebrick: '#b22222',
//   floralwhite: '#fffaf0',
//   forestgreen: '#228b22',
//   fuchsia: '#ff00ff',
//   gainsboro: '#dcdcdc',
//   ghostwhite: '#f8f8ff',
//   gold: '#ffd700',
//   goldenrod: '#daa520',
//   greenyellow: '#adff2f',
//   gray: '#e5e5e5',
//   honeydew: '#f0fff0',
//   hotpink: '#ff69b4',
//   indianred: '#cd5c5c',
//   indigo: '#4b0082',
//   ivory: '#fffff0',
//   khaki: '#f0e68c',
//   lavender: '#e6e6fa',
//   lavenderblush: '#fff0f5',
//   lawngreen: '#7cfc00',
//   lemonchiffon: '#fffacd',
//   lightblue: '#add8e6',
//   lightcoral: '#f08080',
//   lightcyan: '#e0ffff',
//   lightgoldenrodyellow: '#fafad2',
//   lightgreen: '#90ee90',
//   lightpink: '#ffb6c1',
//   lightsalmon: '#ffa07a',
//   lightseagreen: '#20b2aa',
//   lightskyblue: '#87cefa',
//   lightslategray: '#778899',
//   lightsteelblue: '#b0c4de',
//   lightyellow: '#ffffe0',
//   lime: '#00ff00',
//   limegreen: '#32cd32',
//   linen: '#faf0e6',
//   magenta: '#ff00ff',
//   maroon: '#800000',
//   mediumaquamarine: '#66cdaa',
//   midnightblue: '#191970',
//   mintcream: '#f5fffa',
//   mistyrose: '#ffe4e1',
//   moccasin: '#ffe4b5',
//   navajowhite: '#ffdead',
//   navy: '#000080',
//   oldlace: '#fdf5e6',
//   olive: '#808000',
//   olivedrab: '#6b8e23',
//   orange: '#ffa500',
//   orangered: '#ff4500',
//   orchid: '#da70d6',
//   palegoldenrod: '#eee8aa',
//   palegray: '#d3d3d3',
//   palegreen: '#98fb98',
//   paleturquoise: '#afeeee',
//   palevioletred: '#db7093',
//   papayawhip: '#ffefd5',
//   peachpuff: '#ffdab9',
//   peru: '#cd853f',
//   pink: '#ffc0cb',
//   plum: '#dda0dd',
//   powderblue: '#b0e0e6',
//   purple: '#800080',
//   rebeccapurple: '#663399',
//   rosybrown: '#bc8f8f',
//   royalblue: '#4169e1',
//   royalblueDark: '#0457fd',
//   saddlebrown: '#8b4513',
//   salmon: '#fa8072',
//   sandybrown: '#f4a460',
//   seagreen: '#2e8b57',
//   seashell: '#fff5ee',
//   sienna: '#a0522d',
//   silver: '#c0c0c0',
//   skyblue: '#87ceeb',
//   slateblue: '#6a5acd',
//   slategray: '#708090',
//   snow: '#fffafa',
//   springgreen: '#00ff7f',
//   steelblue: '#4682b4',
//   tan: '#d2b48c',
//   teal: '#008080',
//   thistle: '#d8bfd8',
//   tomato: '#ff6347',
//   turquoise: '#40e0d0',
//   violet: '#ee82ee',
//   wheat: '#f5deb3',
//   whitesmoke: '#f5f5f5',
//   yellow: '#ffd200',
// };
