const events = [
    {
      day: 3,
      description: 'Medicine Reminder',
      month: 'Nov',
      monthNo: 11,
      name: 'Pooja',
      time: '10:30 pm - 11:00 pm',
      week: 'Tue',
      survey: false,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      year: 2023,
    },
    {
      day: 3,
      description:
        'Regular CheckUp Regular CheckUpRegular CheckUpRegular CheckUpRegular CheckUp ',
      month: 'Nov',
      monthNo: 11,
      name: 'John',
      time: '10:30 pm - 11:00 pm',
      week: 'Tue',
      year: 2023,
      survey: true,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 26,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Pooja',
      time: '8:25 am - 9:25 am',
      week: 'Wed',
      year: 2023,
      survey: true,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    },
    {
      day: 26,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Krishna',
      time: '8:51 pm - 9:51 pm',
      week: 'Sat',
      year: 2001,
      survey: true,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    },
    {
      day: 9,
      description: 'Medicine Reminder',
      month: 'Aug',
      monthNo: 8,
      name: 'Lisa',
      time: '9:08 am - 10:08 am',
      week: 'Mon',
      year: 2018,
      survey: true,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 26,
      description: 'Medicine Reminder',
      month: 'Oct',
      monthNo: 10,
      name: 'Emma',
      time: '10:50 pm - 11:50 pm',
      week: 'Wed',
      year: 2034,
      survey: true,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 4,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Emma',
      time: '9:15 am - 10:15 am',
      week: 'Sat',
      year: 2023,
      survey: true,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 20,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Krishna',
      time: '4:54 pm - 5:54 pm',
      week: 'Thu',
      year: 2029,
      survey: true,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 3,
      description:
        'Dental Appointmentknknknkndknlknkdnmdn kj nksmn cm  dkcnkxckn',
      month: 'Jun',
      monthNo: 6,
      name: 'Ram',
      time: '2:30 am - 3:30 am',
      week: 'Sun',
      year: 2025,
      survey: false,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 1,
      description: 'Dental Appointment',
      month: 'Nov',
      monthNo: 11,
      name: 'Krishna',
      time: '3:56 am - 4:56 am',
      week: 'Sun',
      year: 2004,
      survey: true,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/428361/pexels-photo-428361.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 5,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Emma',
      time: '9:19 pm - 10:19 pm',
      week: 'Sat',
      survey: false,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
      year: 2012,
    },
    {
      day: 17,
      description: 'Dental Appointment',
      month: 'Jan',
      monthNo: 1,
      name: 'John',
      time: '11:59 pm - 12:59 pm',
      week: 'Sat',
      survey: true,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/428361/pexels-photo-428361.jpeg?auto=compress&cs=tinysrgb&w=600',
      year: 2026,
    },
    {
      day: 14,
      description: 'Dental Appointment',
      month: 'Aug',
      monthNo: 8,
      name: 'Krishna',
      time: '2:49 am - 3:49 am',
      week: 'Wed',
      survey: false,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/428361/pexels-photo-428361.jpeg?auto=compress&cs=tinysrgb&w=600',
      year: 2030,
    },
    {
      day: 17,
      description: 'Regular CheckUp',
      month: 'Feb',
      monthNo: 2,
      name: 'Emma',
      time: '10:12 am - 11:12 am',
      week: 'Tue',
      survey: false,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      year: 2017,
    },
    {
      day: 26,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Krishna',
      time: '8:51 pm - 9:51 pm',
      week: 'Sat',
      year: 2001,
      survey: true,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    },
    {
      day: 9,
      description: 'Medicine Reminder',
      month: 'Aug',
      monthNo: 8,
      name: 'Lisa',
      time: '9:08 am - 10:08 am',
      week: 'Mon',
      year: 2018,
      survey: true,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 26,
      description: 'Medicine Reminder',
      month: 'Oct',
      monthNo: 10,
      name: 'Emma',
      time: '10:50 pm - 11:50 pm',
      week: 'Wed',
      year: 2034,
      survey: true,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 4,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Emma',
      time: '9:15 am - 10:15 am',
      week: 'Sat',
      year: 2023,
      survey: true,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 20,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Krishna',
      time: '4:54 pm - 5:54 pm',
      week: 'Thu',
      year: 2029,
      survey: true,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 3,
      description:
        'Dental Appointmentknknknkndknlknkdnmdn kj nksmn cm  dkcnkxckn',
      month: 'Jun',
      monthNo: 6,
      name: 'Ram',
      time: '2:30 am - 3:30 am',
      week: 'Sun',
      year: 2025,
      survey: false,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 1,
      description: 'Dental Appointment',
      month: 'Nov',
      monthNo: 11,
      name: 'Krishna',
      time: '3:56 am - 4:56 am',
      week: 'Sun',
      year: 2004,
      survey: true,
      showEH: true,
      profileURL:
        'https://images.pexels.com/photos/428361/pexels-photo-428361.jpeg?auto=compress&cs=tinysrgb&w=600',
    },
    {
      day: 5,
      description: 'Dental Appointment',
      month: 'Oct',
      monthNo: 10,
      name: 'Emma',
      time: '9:19 pm - 10:19 pm',
      week: 'Sat',
      survey: false,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
      year: 2012,
    },
    {
      day: 17,
      description: 'Dental Appointment',
      month: 'Jan',
      monthNo: 1,
      name: 'John',
      time: '11:59 pm - 12:59 pm',
      week: 'Sat',
      survey: true,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/428361/pexels-photo-428361.jpeg?auto=compress&cs=tinysrgb&w=600',
      year: 2026,
    },
    {
      day: 14,
      description: 'Dental Appointment',
      month: 'Aug',
      monthNo: 8,
      name: 'Krishna',
      time: '2:49 am - 3:49 am',
      week: 'Wed',
      survey: false,
      showEH: false,
      profileURL:
        'https://images.pexels.com/photos/428361/pexels-photo-428361.jpeg?auto=compress&cs=tinysrgb&w=600',
      year: 2030,
    },
    {
        day: 24,
        description: 'Medicine Reminder',
        month: 'Oct',
        monthNo: 10,
        name: 'Pooja',
        time: '8:07 pm - 9:07 pm',
        week: 'Tue',
        survey: false,
        showEH: true,
        profileURL:
          'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        year: 2023,
      },
      {
        day: 27,
        description:
          'Regular CheckUp  ',
        month: 'Oct',
        monthNo: 10,
        name: 'John',
        time: '2:01 pm - 3:01 pm',
        week: 'Mon',
        year: 2023,
        survey: true,
        showEH: true,
        profileURL:
          'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600',
      },
      {
        day: 27,
        description: 'Dental Appointment',
        month: 'Oct',
        monthNo: 10,
        name: 'Pooja',
        time: '8:25 am - 9:25 am',
        week: 'Wed',
        year: 2023,
        survey: true,
        showEH: true,
        profileURL:
          'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      },
      {
        day: 27,
        description: 'Dental Appointment',
        month: 'Oct',
        monthNo: 10,
        name: 'Krishna',
        time: '8:51 pm - 9:51 pm',
        week: 'Sat',
        year: 2001,
        survey: true,
        showEH: true,
        profileURL:
          'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      },
      {
        day: 9,
        description: 'Medicine Reminder',
        month: 'Aug',
        monthNo: 8,
        name: 'Lisa',
        time: '9:08 am - 10:08 am',
        week: 'Mon',
        year: 2018,
        survey: true,
        showEH: true,
        profileURL:
          'https://images.pexels.com/photos/1559486/pexels-photo-1559486.jpeg?auto=compress&cs=tinysrgb&w=600',
      },
     

  ];
export default events;